# Generated by Django 3.0.5 on 2020-04-14 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_estimator_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Log',
            new_name='Logs',
        ),
    ]
